spring.application.name=student-course-system
spring.datasource.url=jdbc:mysql://localhost:3306/student_course_db
spring.datasource.username=root
spring.datasource.password=Moha3871@sql

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true